import Head from "next/head";
import type { FC, ReactNode } from "react";
import Navbar from "./Navbar";

interface Props {
  children: ReactNode;
  title?: string;
}

const Layout: FC<Props> = ({ children, title }) => {
  return (
    <div className="flex h-screen flex-col">
      <Head>
        <title>{title ? title : "Carlos Alberto"}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {children}
        </div>
      </main>
    </div>
  );
};

export default Layout;
