import type { FC, ReactNode } from "react";
import Navbar from "./Navbar";
import Head from "next/head";

interface Props {
  children: ReactNode;
  title?: string
}

const Layout: FC<Props> = ({ children, title }) => {

  const aux = title ? title : 'Carlos Alberto'

  return (
    <>
      <Head>
        <title>{aux}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col">
        <Navbar />
        <main className="flex items-center justify-center">
          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
            {children}
          </div>
        </main>
      </div>
    </>
  );
};

export default Layout;
