export const projects = [
  {
    id: 1,
    name: "Portfolio",
    image: "/img/thunder.svg",
    link: "www.google.com",
    github: "www.github.com",
    description: "This very website you're in right now",
  },
  {
    id: 2,
    name: "Portfolio v2",
    image: "/img/thunder.svg",
    link: "www.google.com",
    github: "www.github.com",
    description: "This is a placeholder",
  },
  {
    id: 3,
    name: "Portfolio v3",
    image: "/img/thunder.svg",
    link: "www.google.com",
    github: "www.github.com",
    description: "This very website you're in right now",
  },
  {
    id: 4,
    name: "Portfolio v4",
    image: "/img/thunder.svg",
    link: "www.google.com",
    github: "www.github.com",
    description: "This is a placeholder",
  },
  {
    id: 5,
    name: "Portfolio v5",
    image: "/img/thunder.svg",
    link: "www.google.com",
    github: "www.github.com",
    description: "This very website you're in right now",
  },
  {
    id: 6,
    name: "Portfolio v6",
    image: "/img/thunder.svg",
    link: "www.google.com",
    github: "www.github.com",
    description: "This is a placeholder",
  },
  {
    id: 7,
    name: "Portfolio v7",
    image: "/img/thunder.svg",
    link: "www.google.com",
    github: "www.github.com",
    description: "This very website you're in right now",
  }
];
